const products = [{
        _id: '1',
        name: 'Olami African Print Ballon Sleve',
        image: '/images/female-shirt.jpg',
        description: 'This African print ballon sleeve piece is the combination of sophisticated fashion and comfortability.',
        brand: 'Shirt',
        category: 'Female',
        price: 19.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '2',
        name: 'Bisa Women African Print Layer Necklace',
        image: '/images/female-necklace.jpg',
        description: 'Our Bisa Women African Print Layer Necklace (Mixed Tribal Prints) is essential for elevating any solid colored ensemble.',
        brand: 'Necklece',
        category: 'Female',
        price: 59.99,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
    },
    {
        _id: '3',
        name: 'African Kente Pants-Skinny Side Stripe',
        image: '/images/female-pants.jpg',
        description: 'African Kente Pant With Matching Scarf. These Pants Have Elastic Waist Band And Elastic By Ankle For Tight Fitness.',
        brand: 'Pant',
        category: 'Female',
        price: 29.99,
        countInStock: 5,
        rating: 3,
        numReviews: 12,
    },
    {
        _id: '4',
        name: 'Unisex Dashiki Shirt',
        image: '/images/men-shirt.jpg',
        description: 'Our Unisex dashiki tops suitable for all occasions they are made from 100% African wax cotton. It Fits different shapes and sizes',
        brand: 'Shirt',
        category: 'Male',
        price: 39.99,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
    },
    {
        _id: '5',
        name: 'Brown Men Leather Sandals',
        image: '/images/sandals-men.jpg',
        description: 'Beautiful and vibrant colors.The quality and design is remarkable!',
        brand: 'Sandals',
        category: 'Men',
        price: 49.99,
        countInStock: 7,
        rating: 3.5,
        numReviews: 10,
    },
    {
        _id: '6',
        name: 'African Attire-Men Wedding',
        image: '/images/men-suit.jpg',
        description: 'Mens african clothing heavy fabric looks mud cloth shirt blouse two pockets, pant side pocket & hat!',
        brand: 'Suits',
        category: 'Men',
        price: 129.99,
        countInStock: 0,
        rating: 4,
        numReviews: 12,
    },
]

export default products